export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  className: string;
  accent: string;
  terminal: {
    foreground: string;
    cursor: string;
    selectionBackground: string;
    black: string;
    red: string;
    green: string;
    yellow: string;
    blue: string;
    magenta: string;
    cyan: string;
    white: string;
    brightBlack: string;
    brightRed: string;
    brightGreen: string;
    brightYellow: string;
    brightBlue: string;
    brightMagenta: string;
    brightCyan: string;
    brightWhite: string;
  };
  terminalOptions?: {
    fontFamily?: string;
    fontWeight?: number;
    fontWeightBold?: number;
    lineHeight?: number;
    letterSpacing?: number;
    cursorStyle?: 'block' | 'underline' | 'bar';
    cursorWidth?: number;
  };
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'obsidian',
    name: 'Obsidian',
    description: '深海黑蓝，适合长时间开发。',
    className: '',
    accent: '#60a5fa',
    terminal: {
      foreground: '#dbe7ff',
      cursor: '#7dd3fc',
      selectionBackground: 'rgba(96, 165, 250, 0.30)',
      black: '#0f172a',
      red: '#f87171',
      green: '#4ade80',
      yellow: '#fbbf24',
      blue: '#60a5fa',
      magenta: '#c084fc',
      cyan: '#22d3ee',
      white: '#dbe7ff',
      brightBlack: '#475569',
      brightRed: '#fca5a5',
      brightGreen: '#86efac',
      brightYellow: '#fde68a',
      brightBlue: '#93c5fd',
      brightMagenta: '#d8b4fe',
      brightCyan: '#67e8f9',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'graphite',
    name: 'Graphite',
    description: '石墨银灰，克制而专业。',
    className: 'theme-graphite',
    accent: '#94a3b8',
    terminal: {
      foreground: '#e5ecf4',
      cursor: '#cbd5e1',
      selectionBackground: 'rgba(148, 163, 184, 0.28)',
      black: '#111827',
      red: '#f87171',
      green: '#34d399',
      yellow: '#fbbf24',
      blue: '#93c5fd',
      magenta: '#c4b5fd',
      cyan: '#67e8f9',
      white: '#e5ecf4',
      brightBlack: '#6b7280',
      brightRed: '#fca5a5',
      brightGreen: '#6ee7b7',
      brightYellow: '#fde68a',
      brightBlue: '#bfdbfe',
      brightMagenta: '#ddd6fe',
      brightCyan: '#a5f3fc',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'ember',
    name: 'Ember',
    description: '炭黑暖橙，更像高质感控制台。',
    className: 'theme-ember',
    accent: '#fb923c',
    terminal: {
      foreground: '#ffe7cf',
      cursor: '#fb923c',
      selectionBackground: 'rgba(251, 146, 60, 0.28)',
      black: '#1c1917',
      red: '#fb7185',
      green: '#4ade80',
      yellow: '#fbbf24',
      blue: '#fdba74',
      magenta: '#f0abfc',
      cyan: '#67e8f9',
      white: '#ffe7cf',
      brightBlack: '#57534e',
      brightRed: '#fda4af',
      brightGreen: '#86efac',
      brightYellow: '#fde68a',
      brightBlue: '#fed7aa',
      brightMagenta: '#f5d0fe',
      brightCyan: '#a5f3fc',
      brightWhite: '#fff7ed',
    },
  },
  {
    id: 'aurora',
    name: 'Aurora',
    description: '青绿冷光，适合 Agent 工作流视图。',
    className: 'theme-aurora',
    accent: '#2dd4bf',
    terminal: {
      foreground: '#d6fff7',
      cursor: '#5eead4',
      selectionBackground: 'rgba(45, 212, 191, 0.28)',
      black: '#042f2e',
      red: '#fb7185',
      green: '#2dd4bf',
      yellow: '#facc15',
      blue: '#38bdf8',
      magenta: '#c084fc',
      cyan: '#5eead4',
      white: '#d6fff7',
      brightBlack: '#4b5563',
      brightRed: '#fda4af',
      brightGreen: '#99f6e4',
      brightYellow: '#fde68a',
      brightBlue: '#7dd3fc',
      brightMagenta: '#ddd6fe',
      brightCyan: '#ccfbf1',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'porcelain',
    name: 'Porcelain',
    description: '通透白色，适合清爽信息密度型界面。',
    className: 'theme-porcelain',
    accent: '#4f46e5',
    terminal: {
      foreground: '#f8fbff',
      cursor: '#a5b4fc',
      selectionBackground: 'rgba(129, 140, 248, 0.24)',
      black: '#1f2a44',
      red: '#fda4af',
      green: '#86efac',
      yellow: '#fde68a',
      blue: '#c7d2fe',
      magenta: '#ddd6fe',
      cyan: '#bfdbfe',
      white: '#eef4ff',
      brightBlack: '#64748b',
      brightRed: '#fecdd3',
      brightGreen: '#bbf7d0',
      brightYellow: '#fef3c7',
      brightBlue: '#e0e7ff',
      brightMagenta: '#ede9fe',
      brightCyan: '#dbeafe',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'meadow',
    name: 'Meadow',
    description: '绿色清新，带一点植物感和工作台呼吸感。',
    className: 'theme-meadow',
    accent: '#22c55e',
    terminal: {
      foreground: '#f5fff8',
      cursor: '#86efac',
      selectionBackground: 'rgba(74, 222, 128, 0.24)',
      black: '#123524',
      red: '#fda4af',
      green: '#86efac',
      yellow: '#fde68a',
      blue: '#bbf7d0',
      magenta: '#d8b4fe',
      cyan: '#99f6e4',
      white: '#ecfdf5',
      brightBlack: '#5b7c69',
      brightRed: '#fecdd3',
      brightGreen: '#dcfce7',
      brightYellow: '#fef3c7',
      brightBlue: '#d1fae5',
      brightMagenta: '#ede9fe',
      brightCyan: '#ccfbf1',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    description: '浅色奶霜 flavor，配细条光标和更紧凑的字面节奏。',
    className: 'theme-catppuccin-latte',
    accent: '#1e66f5',
    terminal: {
      foreground: '#4c4f69',
      cursor: '#1e66f5',
      selectionBackground: 'rgba(30, 102, 245, 0.18)',
      black: '#5c5f77',
      red: '#d20f39',
      green: '#40a02b',
      yellow: '#df8e1d',
      blue: '#1e66f5',
      magenta: '#ea76cb',
      cyan: '#179299',
      white: '#acb0be',
      brightBlack: '#6c6f85',
      brightRed: '#d20f39',
      brightGreen: '#40a02b',
      brightYellow: '#df8e1d',
      brightBlue: '#1e66f5',
      brightMagenta: '#ea76cb',
      brightCyan: '#179299',
      brightWhite: '#4c4f69',
    },
    terminalOptions: {
      fontWeight: 520,
      fontWeightBold: 720,
      cursorStyle: 'bar',
      cursorWidth: 2,
    },
  },
  {
    id: 'catppuccin-frappe',
    name: 'Catppuccin Frappe',
    description: '冷调雾蓝 flavor，配下划线光标和更轻的等宽质感。',
    className: 'theme-catppuccin-frappe',
    accent: '#8caaee',
    terminal: {
      foreground: '#c6d0f5',
      cursor: '#8caaee',
      selectionBackground: 'rgba(140, 170, 238, 0.22)',
      black: '#51576d',
      red: '#e78284',
      green: '#a6d189',
      yellow: '#e5c890',
      blue: '#8caaee',
      magenta: '#f4b8e4',
      cyan: '#81c8be',
      white: '#b5bfe2',
      brightBlack: '#626880',
      brightRed: '#ea999c',
      brightGreen: '#b8dba2',
      brightYellow: '#eed49f',
      brightBlue: '#99b5ef',
      brightMagenta: '#f2d5cf',
      brightCyan: '#85c1dc',
      brightWhite: '#cdd6f4',
    },
    terminalOptions: {
      fontWeight: 430,
      fontWeightBold: 640,
      cursorStyle: 'underline',
    },
  },
  {
    id: 'catppuccin-macchiato',
    name: 'Catppuccin Macchiato',
    description: '深海蓝黑 flavor，配更稳重的块状光标和更宽松行距。',
    className: 'theme-catppuccin-macchiato',
    accent: '#8aadf4',
    terminal: {
      foreground: '#cad3f5',
      cursor: '#8aadf4',
      selectionBackground: 'rgba(138, 173, 244, 0.22)',
      black: '#494d64',
      red: '#ed8796',
      green: '#a6da95',
      yellow: '#eed49f',
      blue: '#8aadf4',
      magenta: '#f5bde6',
      cyan: '#8bd5ca',
      white: '#b8c0e0',
      brightBlack: '#5b6078',
      brightRed: '#ee99a0',
      brightGreen: '#b1e3ad',
      brightYellow: '#f0dba8',
      brightBlue: '#9abdf5',
      brightMagenta: '#f5c2e7',
      brightCyan: '#91d7cf',
      brightWhite: '#cad3f5',
    },
    terminalOptions: {
      fontWeight: 520,
      fontWeightBold: 760,
      cursorStyle: 'block',
    },
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    description: '经典暗色 flavor，配细竖光标和更显眼的终端字距。',
    className: 'theme-catppuccin-mocha',
    accent: '#89b4fa',
    terminal: {
      foreground: '#cdd6f4',
      cursor: '#89b4fa',
      selectionBackground: 'rgba(137, 180, 250, 0.22)',
      black: '#45475a',
      red: '#f38ba8',
      green: '#a6e3a1',
      yellow: '#f9e2af',
      blue: '#89b4fa',
      magenta: '#f5c2e7',
      cyan: '#94e2d5',
      white: '#bac2de',
      brightBlack: '#585b70',
      brightRed: '#f2a0b7',
      brightGreen: '#b4e8b0',
      brightYellow: '#f9e2af',
      brightBlue: '#a6c8ff',
      brightMagenta: '#f5c2e7',
      brightCyan: '#a8e6df',
      brightWhite: '#cdd6f4',
    },
    terminalOptions: {
      fontWeight: 470,
      fontWeightBold: 700,
      cursorStyle: 'bar',
      cursorWidth: 3,
    },
  },
];

export const getThemePreset = (themeId: string) =>
  THEME_PRESETS.find(theme => theme.id === themeId) || THEME_PRESETS[0];
